// Workout Tracker – Exercise & Workout Data
// All P90X workout programs with exercise definitions.
// Loaded before the main app script via <script src>.

/* ── Exercise Types ── */
const ExType = { REPS_WEIGHT: 'reps_weight', REPS_ONLY: 'reps_only', LEFT_RIGHT: 'left_right', DURATION: 'duration' };

/* ── Exercise Definitions ── */
const EXERCISES = {
  // === CHEST & BACK (Disc 1) ===
  "cb-standard-pushups": { id: "cb-standard-pushups", name: "Standard Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Chest: hands shoulder-width apart, full range of motion" },
  "cb-wide-front-pullups": { id: "cb-wide-front-pullups", name: "Wide Front Pull-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: wide overhand grip pull-ups" },
  "cb-military-pushups": { id: "cb-military-pushups", name: "Military Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Chest: hands close together, elbows tight to body" },
  "cb-reverse-grip-chinups": { id: "cb-reverse-grip-chinups", name: "Reverse Grip Chin-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: underhand grip chin-ups" },
  "cb-wide-fly-pushups": { id: "cb-wide-fly-pushups", name: "Wide Fly Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Chest: arms wide, fly motion on the way up" },
  "cb-closed-grip-overhand-pullups": { id: "cb-closed-grip-overhand-pullups", name: "Closed Grip Overhand Pull-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: hands close together, overhand grip" },
  "cb-decline-pushups": { id: "cb-decline-pushups", name: "Decline Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Chest: feet elevated on chair or bench" },
  "cb-heavy-pants": { id: "cb-heavy-pants", name: "Heavy Pants", type: ExType.REPS_WEIGHT, defaultDescription: "Back: bent-over row, pull dumbbells up like pulling up pants" },
  "cb-diamond-pushups": { id: "cb-diamond-pushups", name: "Diamond Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Chest: hands in diamond shape under chest" },
  "cb-lawnmowers": { id: "cb-lawnmowers", name: "Lawnmowers", type: ExType.REPS_WEIGHT, defaultDescription: "Back: single-arm row with twist, like starting a lawnmower" },
  "cb-dive-bomber-pushups": { id: "cb-dive-bomber-pushups", name: "Dive-Bomber Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Chest: start in pike, swoop down and through, reverse" },
  "cb-back-flys": { id: "cb-back-flys", name: "Back Flys", type: ExType.REPS_WEIGHT, defaultDescription: "Back: bent over, raise dumbbells out to sides" },

  // === SHOULDERS & ARMS (Disc 3) ===
  "sa-alt-shoulder-press": { id: "sa-alt-shoulder-press", name: "Alternating Shoulder Presses", type: ExType.REPS_WEIGHT, defaultDescription: "Shoulders: alternating dumbbell press overhead" },
  "sa-in-out-bicep-curls": { id: "sa-in-out-bicep-curls", name: "In & Out Bicep Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: alternate between wide and narrow curls" },
  "sa-two-arm-tricep-kickback": { id: "sa-two-arm-tricep-kickback", name: "Two-Arm Triceps Kickback", type: ExType.REPS_WEIGHT, defaultDescription: "Triceps: bent over, extend both arms back" },
  "sa-deep-swimmers-press": { id: "sa-deep-swimmers-press", name: "Deep Swimmer's Presses", type: ExType.REPS_WEIGHT, defaultDescription: "Shoulders: squat down, press up with rotation" },
  "sa-full-supination-curls": { id: "sa-full-supination-curls", name: "Full Supination Concentration Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: seated concentration curl with full wrist rotation" },
  "sa-chair-dips": { id: "sa-chair-dips", name: "Chair Dips", type: ExType.REPS_ONLY, defaultDescription: "Triceps: dips using a chair, hands behind you" },
  "sa-upright-rows": { id: "sa-upright-rows", name: "Upright Rows", type: ExType.REPS_WEIGHT, defaultDescription: "Shoulders: pull dumbbells straight up to chin" },
  "sa-static-arm-curls": { id: "sa-static-arm-curls", name: "Static Arm Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: one arm holds at 90 degrees while other curls" },
  "sa-flip-grip-kickbacks": { id: "sa-flip-grip-kickbacks", name: "Flip-Grip Twist Triceps Kickbacks", type: ExType.REPS_WEIGHT, defaultDescription: "Triceps: kickback with a grip flip at the top" },
  "sa-two-angle-shoulder-flys": { id: "sa-two-angle-shoulder-flys", name: "Seated Two-Angle Shoulder Flys", type: ExType.REPS_WEIGHT, defaultDescription: "Shoulders: seated lateral raises at two different angles" },
  "sa-crouching-cohen-curls": { id: "sa-crouching-cohen-curls", name: "Crouching Cohen Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: wide squat stance, curl with elbows on knees" },
  "sa-lying-tricep-ext": { id: "sa-lying-tricep-ext", name: "Lying-Down Triceps Extensions", type: ExType.REPS_WEIGHT, defaultDescription: "Triceps: lying on back, lower dumbbells behind head" },
  "sa-in-out-shoulder-flys": { id: "sa-in-out-shoulder-flys", name: "In & Out Straight-Arm Shoulder Flys", type: ExType.REPS_WEIGHT, defaultDescription: "Shoulders: alternate between front raise and lateral raise" },
  "sa-congdon-curls": { id: "sa-congdon-curls", name: "Congdon Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: curl up normally, lower only halfway, back up, then full lower" },
  "sa-side-tri-rises": { id: "sa-side-tri-rises", name: "Side Tri-Rises", type: ExType.LEFT_RIGHT, defaultDescription: "Triceps: lying on side, push upper body up with one arm" },

  // === LEGS & BACK (Disc 5) ===
  "lb-balanced-lunges": { id: "lb-balanced-lunges", name: "Balanced Lunges", type: ExType.LEFT_RIGHT, defaultDescription: "Legs: forward lunges, alternating legs" },
  "lb-calf-raise-squats": { id: "lb-calf-raise-squats", name: "Calf-Raise Squats", type: ExType.REPS_WEIGHT, defaultDescription: "Legs: squat then calf raise at the top" },
  "lb-reverse-grip-chinups": { id: "lb-reverse-grip-chinups", name: "Reverse Grip Chin-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: underhand grip chin-ups" },
  "lb-super-skaters": { id: "lb-super-skaters", name: "Super Skaters", type: ExType.LEFT_RIGHT, defaultDescription: "Legs: single-leg squat reaching across, like a speed skater" },
  "lb-wall-squats": { id: "lb-wall-squats", name: "Wall Squats", type: ExType.DURATION, defaultDescription: "Legs: back against wall, sit at 90 degrees and hold", durationSec: 90 },
  "lb-wide-front-pullups": { id: "lb-wide-front-pullups", name: "Wide Front Pull-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: wide overhand grip pull-ups" },
  "lb-step-back-lunge": { id: "lb-step-back-lunge", name: "Step Back Lunge", type: ExType.REPS_WEIGHT, defaultDescription: "Legs: reverse lunge stepping backward with dumbbells" },
  "lb-alt-side-lunge": { id: "lb-alt-side-lunge", name: "Alternating Side Lunge", type: ExType.REPS_WEIGHT, defaultDescription: "Legs: lateral lunges alternating sides with dumbbells" },
  "lb-closed-grip-pullups": { id: "lb-closed-grip-pullups", name: "Closed Grip Overhand Pull-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: hands close together, overhand grip" },
  "lb-single-leg-wall-squat": { id: "lb-single-leg-wall-squat", name: "Single-Leg Wall Squat", type: ExType.DURATION, defaultDescription: "Legs: wall squat on one leg, other leg extended", durationSec: 60 },
  "lb-deadlift-squats": { id: "lb-deadlift-squats", name: "Deadlift Squats", type: ExType.LEFT_RIGHT, defaultDescription: "Legs: single-leg deadlift with dumbbells" },
  "lb-switch-grip-pullups": { id: "lb-switch-grip-pullups", name: "Switch Grip Pull-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: switch grip every 2 reps between overhand and underhand" },
  "lb-three-way-lunge": { id: "lb-three-way-lunge", name: "Three-Way Lunge", type: ExType.LEFT_RIGHT, defaultDescription: "Legs: forward, side, and reverse lunge in sequence" },
  "lb-sneaky-lunge": { id: "lb-sneaky-lunge", name: "Sneaky Lunge", type: ExType.REPS_ONLY, defaultDescription: "Legs: low crouching walk forward and back" },
  "lb-chair-salutations": { id: "lb-chair-salutations", name: "Chair Salutations", type: ExType.DURATION, defaultDescription: "Legs: chair pose to standing, salutation movement", durationSec: 60 },
  "lb-toe-roll-iso-lunge": { id: "lb-toe-roll-iso-lunge", name: "Toe-Roll Iso Lunge", type: ExType.REPS_WEIGHT, defaultDescription: "Legs: isometric lunge with toe rolls" },
  "lb-groucho-walk": { id: "lb-groucho-walk", name: "Groucho Walk", type: ExType.DURATION, defaultDescription: "Legs: low squat walk, staying low the whole time", durationSec: 60 },
  "lb-calf-raises-toes-out": { id: "lb-calf-raises-toes-out", name: "Calf Raises - Toes Out", type: ExType.REPS_WEIGHT, defaultDescription: "Legs: calf raises with toes pointed outward" },
  "lb-calf-raises-parallel": { id: "lb-calf-raises-parallel", name: "Calf Raises - Feet Parallel", type: ExType.REPS_WEIGHT, defaultDescription: "Legs: calf raises with feet parallel" },
  "lb-calf-raises-toes-in": { id: "lb-calf-raises-toes-in", name: "Calf Raises - Toes In", type: ExType.REPS_WEIGHT, defaultDescription: "Legs: calf raises with toes pointed inward" },
  "lb-closed-grip-pullups-2": { id: "lb-closed-grip-pullups-2", name: "Closed Grip Overhand Pull-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: hands close together, overhand grip" },
  "lb-80-20-squats": { id: "lb-80-20-squats", name: "80/20 Siebers-Speed Squats", type: ExType.LEFT_RIGHT, defaultDescription: "Legs: 80% weight on one leg, 20% on other, fast squats" },
  "lb-switch-grip-pullups-2": { id: "lb-switch-grip-pullups-2", name: "Switch Grip Pull-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: switch grip every 2 reps" },

  // === CORE SYNERGISTICS (Disc 8) ===
  "cs-stacked-staggered-pushups": { id: "cs-stacked-staggered-pushups", name: "Stacked Foot/Staggered Hands Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Switch every 5 reps; stack feet, stagger hand placement" },
  "cs-banana-rolls": { id: "cs-banana-rolls", name: "Banana Rolls", type: ExType.REPS_ONLY, defaultDescription: "16 reps / 2 min: roll from banana (supine) to superman (prone)" },
  "cs-leaning-crescent-lunges": { id: "cs-leaning-crescent-lunges", name: "Leaning Crescent Lunges", type: ExType.REPS_WEIGHT, defaultDescription: "Lunge with torso lean and dumbbells" },
  "cs-squat-runs": { id: "cs-squat-runs", name: "Squat Runs", type: ExType.REPS_WEIGHT, defaultDescription: "Staggered squat with running arm motion, holding dumbbells" },
  "cs-sphinx-pushups": { id: "cs-sphinx-pushups", name: "Sphinx Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Forearms to full arm push-ups, like rising from sphinx position" },
  "cs-bow-to-boat": { id: "cs-bow-to-boat", name: "Bow to Boat", type: ExType.REPS_ONLY, defaultDescription: "4 sets: flip between bow pose (prone) and boat pose (supine)" },
  "cs-low-lateral-skaters": { id: "cs-low-lateral-skaters", name: "Low Lateral Skaters", type: ExType.REPS_ONLY, defaultDescription: "Low lateral hops like a speed skater" },
  "cs-lunge-reach": { id: "cs-lunge-reach", name: "Lunge & Reach", type: ExType.REPS_WEIGHT, defaultDescription: "Lunge forward and reach dumbbell overhead" },
  "cs-prison-cell-pushups": { id: "cs-prison-cell-pushups", name: "Prison Cell Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Push-up, stand up, squat, back to push-up" },
  "cs-side-hip-raise": { id: "cs-side-hip-raise", name: "Side Hip Raise", type: ExType.LEFT_RIGHT, defaultDescription: "Side plank with hip raises" },
  "cs-squat-xpress": { id: "cs-squat-xpress", name: "Squat X-Press", type: ExType.REPS_WEIGHT, defaultDescription: "Squat down, press dumbbells overhead in X-pattern at top" },
  "cs-plank-chaturanga-run": { id: "cs-plank-chaturanga-run", name: "Plank to Chaturanga Run", type: ExType.REPS_ONLY, defaultDescription: "Plank position, lower to chaturanga, run knees to chest" },
  "cs-walking-pushups": { id: "cs-walking-pushups", name: "Walking Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Walk hands side to side between push-ups" },
  "cs-superman-banana": { id: "cs-superman-banana", name: "Superman Banana", type: ExType.REPS_ONLY, defaultDescription: "Alternate between superman (prone) and banana (supine) hold" },
  "cs-lunge-kickback-curl-press": { id: "cs-lunge-kickback-curl-press", name: "Lunge Kickback Curl Press", type: ExType.REPS_WEIGHT, defaultDescription: "Lunge, tricep kickback, curl, shoulder press combo" },
  "cs-towel-hoppers": { id: "cs-towel-hoppers", name: "Towel Hoppers", type: ExType.REPS_ONLY, defaultDescription: "Hop over a towel laterally in push-up position" },
  "cs-reach-high-under-pushups": { id: "cs-reach-high-under-pushups", name: "Reach High & Under Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Push-up, reach one arm high, then thread under body" },
  "cs-steam-engine": { id: "cs-steam-engine", name: "Steam Engine", type: ExType.REPS_ONLY, defaultDescription: "Standing: hands behind head, elbow to opposite knee" },
  "cs-dreya-rolls": { id: "cs-dreya-rolls", name: "Dreya Rolls", type: ExType.REPS_ONLY, defaultDescription: "Roll backward on ground, roll forward and jump up" },
  "cs-plank-chaturanga-iso": { id: "cs-plank-chaturanga-iso", name: "Plank to Chaturanga Iso", type: ExType.REPS_ONLY, defaultDescription: "Plank to chaturanga hold, isometric" },
  "cs-halfback": { id: "cs-halfback", name: "Halfback", type: ExType.REPS_ONLY, defaultDescription: "Quick feet in place, drop and sprint on command" },
  "cs-table-dip-leg-raises": { id: "cs-table-dip-leg-raises", name: "Table Dip Leg Raises", type: ExType.REPS_ONLY, defaultDescription: "Reverse table position, dip while raising alternate legs" },

  // === CHEST, SHOULDERS & TRICEPS (Disc 9) ===
  "cst-slow-motion-3in1-pushups": { id: "cst-slow-motion-3in1-pushups", name: "Slow-Motion 3-in-1 Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Chest: slow push-ups at 3 hand widths" },
  "cst-in-out-shoulder-flys": { id: "cst-in-out-shoulder-flys", name: "In & Out Shoulder Flys", type: ExType.REPS_WEIGHT, defaultDescription: "Shoulders: alternate front raise and lateral raise" },
  "cst-chair-dips": { id: "cst-chair-dips", name: "Chair Dips", type: ExType.REPS_ONLY, defaultDescription: "Triceps: dips from a chair" },
  "cst-plange-pushups": { id: "cst-plange-pushups", name: "Plange Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Chest: hands by hips, lean forward into push-up" },
  "cst-pike-presses": { id: "cst-pike-presses", name: "Pike Presses", type: ExType.REPS_ONLY, defaultDescription: "Shoulders: pike position (hips high) push-ups targeting shoulders" },
  "cst-side-tri-rises": { id: "cst-side-tri-rises", name: "Side Tri-Rises", type: ExType.LEFT_RIGHT, defaultDescription: "Triceps: lying on side, push body up with one arm" },
  "cst-floor-flys": { id: "cst-floor-flys", name: "Floor Flys", type: ExType.REPS_ONLY, defaultDescription: "Chest: push-up position, hands on towels, fly out and in; switch every 4 reps" },
  "cst-scarecrows": { id: "cst-scarecrows", name: "Scarecrows", type: ExType.REPS_WEIGHT, defaultDescription: "Shoulders: bent over, raise to scarecrow position, rotate forearms up" },
  "cst-overhead-tricep-ext": { id: "cst-overhead-tricep-ext", name: "Overhead Triceps Extensions", type: ExType.REPS_WEIGHT, defaultDescription: "Triceps: raise dumbbell overhead, lower behind head" },
  "cst-two-twitch-pushups": { id: "cst-two-twitch-pushups", name: "Two-Twitch Speed Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Chest: 4 fast push-ups then 3 slow push-ups" },
  "cst-y-presses": { id: "cst-y-presses", name: "Y-Presses", type: ExType.REPS_WEIGHT, defaultDescription: "Shoulders: press dumbbells up and out in a Y shape" },
  "cst-lying-tricep-ext": { id: "cst-lying-tricep-ext", name: "Lying Triceps Extensions", type: ExType.REPS_WEIGHT, defaultDescription: "Triceps: lying down, lower dumbbells behind head" },
  "cst-side-to-side-pushups": { id: "cst-side-to-side-pushups", name: "Side-to-Side Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Chest: shift weight side to side during push-ups" },
  "cst-pour-flys": { id: "cst-pour-flys", name: "Pour Flys", type: ExType.REPS_WEIGHT, defaultDescription: "Shoulders: lateral raise with thumbs-down pouring motion" },
  "cst-side-leaning-tricep-ext": { id: "cst-side-leaning-tricep-ext", name: "Side-Leaning Triceps Extensions", type: ExType.REPS_WEIGHT, defaultDescription: "Triceps: lean to one side, extend dumbbell overhead" },
  "cst-one-arm-pushups": { id: "cst-one-arm-pushups", name: "One-Arm Push-Ups", type: ExType.LEFT_RIGHT, defaultDescription: "Chest: push-ups on one arm" },
  "cst-weighted-circles": { id: "cst-weighted-circles", name: "Weighted Circles", type: ExType.REPS_WEIGHT, defaultDescription: "Shoulders: arms out, small circles with dumbbells (2x20 reps)" },
  "cst-throw-the-bomb": { id: "cst-throw-the-bomb", name: "Throw the Bomb", type: ExType.REPS_WEIGHT, defaultDescription: "Triceps: overhead throw motion with dumbbell" },
  "cst-clap-plyo-pushups": { id: "cst-clap-plyo-pushups", name: "Clap or Plyo Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Chest: explosive push-up with clap at top" },
  "cst-slo-mo-throws": { id: "cst-slo-mo-throws", name: "Slo-Mo Throws", type: ExType.REPS_WEIGHT, defaultDescription: "Shoulders: slow overhead throw motion with dumbbells" },
  "cst-front-back-tricep-ext": { id: "cst-front-back-tricep-ext", name: "Front-to-Back Triceps Extensions", type: ExType.REPS_WEIGHT, defaultDescription: "Triceps: extend dumbbell forward, then backward" },
  "cst-one-arm-balance-pushups": { id: "cst-one-arm-balance-pushups", name: "One-Arm Balance Push-Ups", type: ExType.REPS_ONLY, defaultDescription: "Chest: push-up, lift one arm at top for balance" },
  "cst-fly-row-presses": { id: "cst-fly-row-presses", name: "Fly-Row-Presses", type: ExType.REPS_WEIGHT, defaultDescription: "Shoulders: lateral fly, then row, then press - combo move" },
  "cst-dumbbell-cross-body-blows": { id: "cst-dumbbell-cross-body-blows", name: "Dumbbell Cross-Body Blows", type: ExType.REPS_WEIGHT, defaultDescription: "Triceps: cross-body punching motion with dumbbells" },

  // === BACK & BICEPS (Disc 10) ===
  "bb-wide-front-pullups": { id: "bb-wide-front-pullups", name: "Wide Front Pull-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: wide overhand grip pull-ups" },
  "bb-lawnmowers": { id: "bb-lawnmowers", name: "Lawnmowers", type: ExType.REPS_WEIGHT, defaultDescription: "Back: single-arm row with twist" },
  "bb-twenty-ones": { id: "bb-twenty-ones", name: "Twenty-Ones", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: 7 lower half, 7 upper half, 7 full range curls" },
  "bb-one-arm-cross-body-curls": { id: "bb-one-arm-cross-body-curls", name: "One-Arm Cross-Body Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: curl dumbbell across body toward opposite shoulder" },
  "bb-switch-grip-pullups": { id: "bb-switch-grip-pullups", name: "Switch Grip Pull-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: switch grip every 2 reps" },
  "bb-elbows-out-lawnmowers": { id: "bb-elbows-out-lawnmowers", name: "Elbows-Out Lawnmowers", type: ExType.REPS_WEIGHT, defaultDescription: "Back: lawnmower row but elbows flare out to sides" },
  "bb-standing-bicep-curls": { id: "bb-standing-bicep-curls", name: "Standing Bicep Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: standard standing dumbbell curls" },
  "bb-one-arm-concentration-curls": { id: "bb-one-arm-concentration-curls", name: "One-Arm Concentration Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: seated, elbow on inner thigh, curl one arm" },
  "bb-corn-cob-pullups": { id: "bb-corn-cob-pullups", name: "Corn Cob Pull-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: pull up, then slide side to side at the top like eating corn" },
  "bb-reverse-grip-rows": { id: "bb-reverse-grip-rows", name: "Reverse Grip Bent-Over Rows", type: ExType.REPS_WEIGHT, defaultDescription: "Back: bent over, underhand grip row" },
  "bb-open-arm-curls": { id: "bb-open-arm-curls", name: "Open-Arm Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: arms out wide, curl dumbbells to shoulders" },
  "bb-static-arm-curls": { id: "bb-static-arm-curls", name: "Static-Arm Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: hold one arm at 90, curl the other, switch" },
  "bb-towel-pullups": { id: "bb-towel-pullups", name: "Towel Pull-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: drape towel over bar, grip towel, pull up; switch every 3" },
  "bb-congdon-locomotives": { id: "bb-congdon-locomotives", name: "Congdon Locomotives", type: ExType.REPS_WEIGHT, defaultDescription: "Back: bent over, alternating rowing with a locomotive motion" },
  "bb-crouching-cohen-curls": { id: "bb-crouching-cohen-curls", name: "Crouching Cohen Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: wide squat stance, curl with elbows on knees" },
  "bb-one-arm-corkscrew-curls": { id: "bb-one-arm-corkscrew-curls", name: "One-Arm Corkscrew Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: curl with a twisting corkscrew motion" },
  "bb-chinups": { id: "bb-chinups", name: "Chin-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: underhand close-grip chin-ups" },
  "bb-seated-bent-over-back-flys": { id: "bb-seated-bent-over-back-flys", name: "Seated Bent-Over Back Flys", type: ExType.REPS_WEIGHT, defaultDescription: "Back: seated, bent forward, raise dumbbells out to sides" },
  "bb-curl-up-hammer-downs": { id: "bb-curl-up-hammer-downs", name: "Curl-Up/Hammer Downs", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: regular curl up, hammer curl down" },
  "bb-hammer-curls": { id: "bb-hammer-curls", name: "Hammer Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: curl with palms facing each other (hammer grip)" },
  "bb-max-rep-pullups": { id: "bb-max-rep-pullups", name: "Max Rep Pull-Ups", type: ExType.REPS_ONLY, defaultDescription: "Back: as many pull-ups as possible" },
  "bb-superman": { id: "bb-superman", name: "Superman", type: ExType.REPS_ONLY, defaultDescription: "Back: lying prone, lift arms and legs (6 x 10 seconds)" },
  "bb-in-out-hammer-curls": { id: "bb-in-out-hammer-curls", name: "In-Out Hammer Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: alternate narrow and wide hammer curls" },
  "bb-strip-set-curls": { id: "bb-strip-set-curls", name: "Strip-Set Curls", type: ExType.REPS_WEIGHT, defaultDescription: "Biceps: 4 rounds, decrease weight each round, max reps" },

  // === AB RIPPER X (Disc 12) ===
  "ab-in-outs": { id: "ab-in-outs", name: "In & Outs", type: ExType.REPS_ONLY, defaultDescription: "Target 25. Seated, pull knees in and extend legs out" },
  "ab-seated-bicycles": { id: "ab-seated-bicycles", name: "Seated Bicycles", type: ExType.REPS_ONLY, defaultDescription: "Target 25. Seated, pedal legs like riding a bicycle" },
  "ab-reverse-bicycles": { id: "ab-reverse-bicycles", name: "Reverse Bicycles", type: ExType.REPS_ONLY, defaultDescription: "Target 25. Same as bicycles but pedal in reverse" },
  "ab-crunchy-frog": { id: "ab-crunchy-frog", name: "Seated Crunchy Frogs", type: ExType.REPS_ONLY, defaultDescription: "Target 25. Seated, hug knees in then extend arms and legs wide" },
  "ab-crossed-wide-leg-situps": { id: "ab-crossed-wide-leg-situps", name: "Crossed Leg/Wide Leg Sit-Ups", type: ExType.REPS_ONLY, defaultDescription: "Target 25. Alternate crossed legs and wide legs sit-ups" },
  "ab-fifer-scissors": { id: "ab-fifer-scissors", name: "Fifer Scissors", type: ExType.REPS_ONLY, defaultDescription: "Target 25. Lying down, scissor legs up and down" },
  "ab-hip-rock-n-raise": { id: "ab-hip-rock-n-raise", name: "Hip Rock 'n Raise", type: ExType.REPS_ONLY, defaultDescription: "Target 25. Rock hips side to side, then raise straight up" },
  "ab-pulse-ups": { id: "ab-pulse-ups", name: "Pulse-Ups (Heels to Heaven)", type: ExType.REPS_ONLY, defaultDescription: "Target 25. Legs straight up, pulse hips upward" },
  "ab-roll-up-v-up": { id: "ab-roll-up-v-up", name: "Roll-Up/V-Up Combos", type: ExType.REPS_ONLY, defaultDescription: "Target 25. Alternate between roll-ups and V-ups" },
  "ab-oblique-v-ups": { id: "ab-oblique-v-ups", name: "Oblique V-Ups", type: ExType.REPS_ONLY, defaultDescription: "Target 25. Lying on side, V-up for obliques" },
  "ab-leg-climbs": { id: "ab-leg-climbs", name: "Leg Climbs", type: ExType.REPS_ONLY, defaultDescription: "Target 25. One leg up, climb hands up the leg" },
  "ab-mason-twist": { id: "ab-mason-twist", name: "Mason (Kayak) Twist", type: ExType.REPS_ONLY, defaultDescription: "Target 25. Seated, twist torso side to side like paddling a kayak" },

  // === PLYOMETRICS (Disc 2) ===
  "plyo-jump-squats": { id: "plyo-jump-squats", name: "Jump Squats", type: ExType.DURATION, defaultDescription: "Sink into squat then explode upward", durationSec: 30 },
  "plyo-run-stance-squats": { id: "plyo-run-stance-squats", name: "Run Stance Squats", type: ExType.DURATION, defaultDescription: "Boxer's stance squat, leap and switch feet mid-air", durationSec: 30 },
  "plyo-airborne-heisman": { id: "plyo-airborne-heisman", name: "Airborne Heisman", type: ExType.DURATION, defaultDescription: "Leap side-to-side, bring outer knee up into Heisman pose", durationSec: 30 },
  "plyo-swing-kicks": { id: "plyo-swing-kicks", name: "Swing Kicks", type: ExType.DURATION, defaultDescription: "Swing leg over imaginary obstacle, alternate legs", durationSec: 60 },
  "plyo-squat-reach-jumps": { id: "plyo-squat-reach-jumps", name: "Squat Reach Jumps", type: ExType.DURATION, defaultDescription: "Deep squat jumps reaching for maximum height", durationSec: 30 },
  "plyo-squat-switch-pickups": { id: "plyo-squat-switch-pickups", name: "Squat Switch Pickups", type: ExType.DURATION, defaultDescription: "Boxer stance, tap ground, leap and switch feet", durationSec: 30 },
  "plyo-double-airborne-heisman": { id: "plyo-double-airborne-heisman", name: "Double Airborne Heisman", type: ExType.DURATION, defaultDescription: "Stutter-step twice between Heisman knee raises", durationSec: 30 },
  "plyo-circle-run": { id: "plyo-circle-run", name: "Circle Run", type: ExType.DURATION, defaultDescription: "Run in circles around an object, alternating directions", durationSec: 60 },
  "plyo-jump-knee-tucks": { id: "plyo-jump-knee-tucks", name: "Jump Knee Tucks", type: ExType.DURATION, defaultDescription: "Leap up bringing knees above waist, hit open palms", durationSec: 30 },
  "plyo-mary-katherine-lunges": { id: "plyo-mary-katherine-lunges", name: "Mary Katherine Lunges", type: ExType.DURATION, defaultDescription: "Deep lunge, leap and switch feet, arms overhead", durationSec: 30 },
  "plyo-leapfrog-squats": { id: "plyo-leapfrog-squats", name: "Leapfrog Squats", type: ExType.DURATION, defaultDescription: "4 leaps backward in squat, then 4 forward", durationSec: 30 },
  "plyo-twist-combo": { id: "plyo-twist-combo", name: "Twist Combo", type: ExType.DURATION, defaultDescription: "Hop and twist feet side-to-side, add full body rotation", durationSec: 60 },
  "plyo-rock-star-hops": { id: "plyo-rock-star-hops", name: "Rock Star Hops", type: ExType.DURATION, defaultDescription: "Leap diagonally, tuck knees high, air guitar motion", durationSec: 30 },
  "plyo-gap-jumps": { id: "plyo-gap-jumps", name: "Gap Jumps", type: ExType.DURATION, defaultDescription: "Large lateral jumps as if leaping across a gap", durationSec: 30 },
  "plyo-squat-jacks": { id: "plyo-squat-jacks", name: "Squat Jacks", type: ExType.DURATION, defaultDescription: "Hands behind head, jumping jacks in squat position", durationSec: 30 },
  "plyo-military-march": { id: "plyo-military-march", name: "Military March", type: ExType.DURATION, defaultDescription: "Kick leg straight out, opposite arm overhead, robotic march", durationSec: 60 },
  "plyo-run-squat-180": { id: "plyo-run-squat-180", name: "Run Squat 180 Jump Switches", type: ExType.DURATION, defaultDescription: "Squat jumps with 180-degree spin, tap ground", durationSec: 30 },
  "plyo-lateral-leapfrog-squats": { id: "plyo-lateral-leapfrog-squats", name: "Lateral Leapfrog Squats", type: ExType.DURATION, defaultDescription: "From squat, leap sideways with both feet", durationSec: 30 },
  "plyo-monster-truck-tires": { id: "plyo-monster-truck-tires", name: "Monster Truck Tires", type: ExType.DURATION, defaultDescription: "High-knee hops between imaginary tires", durationSec: 30 },
  "plyo-hot-foot": { id: "plyo-hot-foot", name: "Hot Foot", type: ExType.DURATION, defaultDescription: "Hop on one foot tracing a plus-sign; switch at 30s", durationSec: 60 },
  "plyo-pitch-and-catch": { id: "plyo-pitch-and-catch", name: "Pitch and Catch", type: ExType.DURATION, defaultDescription: "Wind up and throw imaginary baseball, 30s each arm", durationSec: 60 },
  "plyo-jump-shots": { id: "plyo-jump-shots", name: "Jump Shots", type: ExType.DURATION, defaultDescription: "Basketball jump shots, 30s each side", durationSec: 60 },
  "plyo-football-hero": { id: "plyo-football-hero", name: "Football Hero / Hustle", type: ExType.DURATION, defaultDescription: "Lateral strides forward, then hustle backward", durationSec: 60 },

  // === KENPO X (Disc 6) ===
  "kx-twist-pivot": { id: "kx-twist-pivot", name: "Twist and Pivot", type: ExType.DURATION, defaultDescription: "Boxing stance, pivot torso and hips rotating elbows", durationSec: 45 },
  "kx-twist-pivot-hook-upper": { id: "kx-twist-pivot-hook-upper", name: "Twist & Pivot w/ Hook Uppercut", type: ExType.DURATION, defaultDescription: "Add hook and uppercut punches to twist and pivot", durationSec: 45 },
  "kx-jabs": { id: "kx-jabs", name: "Jabs", type: ExType.DURATION, defaultDescription: "Straight jabs from boxing stance", durationSec: 45 },
  "kx-jab-cross": { id: "kx-jab-cross", name: "Jab/Cross", type: ExType.DURATION, defaultDescription: "Jab followed by cross punch", durationSec: 45 },
  "kx-jab-cross-hook": { id: "kx-jab-cross-hook", name: "Jab/Cross/Hook", type: ExType.DURATION, defaultDescription: "Three-punch combo building on previous", durationSec: 45 },
  "kx-jab-cross-hook-upper": { id: "kx-jab-cross-hook-upper", name: "Jab/Cross/Hook/Uppercut", type: ExType.DURATION, defaultDescription: "Four-punch combination", durationSec: 45 },
  "kx-step-drag-high-low": { id: "kx-step-drag-high-low", name: "Step Drag Punch High/Low", type: ExType.DURATION, defaultDescription: "Forward step with alternating face and gut punches", durationSec: 45 },
  "kx-jab-cross-switch": { id: "kx-jab-cross-switch", name: "Jab/Cross Switch", type: ExType.DURATION, defaultDescription: "Jab/cross with a jump to switch stance", durationSec: 45 },
  "kx-hook-uppercut-switch": { id: "kx-hook-uppercut-switch", name: "Hook/Uppercut Switch", type: ExType.DURATION, defaultDescription: "Hook/uppercut with a jumping foot switch", durationSec: 45 },
  "kx-knee-kicks": { id: "kx-knee-kicks", name: "Knee Kicks", type: ExType.DURATION, defaultDescription: "High knee strikes", durationSec: 45 },
  "kx-ball-kicks": { id: "kx-ball-kicks", name: "Ball Kicks", type: ExType.DURATION, defaultDescription: "Front kick to waist height, pivoting hips", durationSec: 45 },
  "kx-side-kicks": { id: "kx-side-kicks", name: "Side Kicks", type: ExType.DURATION, defaultDescription: "Waist-height side kicks", durationSec: 45 },
  "kx-back-kicks": { id: "kx-back-kicks", name: "Back Kicks", type: ExType.DURATION, defaultDescription: "Heel kick backward like a mule kick", durationSec: 45 },
  "kx-three-direction-kicks": { id: "kx-three-direction-kicks", name: "Three Direction Kicks", type: ExType.DURATION, defaultDescription: "Front kick, side kick, back kick in sequence", durationSec: 45 },
  "kx-high-sword-low-hammer": { id: "kx-high-sword-low-hammer", name: "High Sword/Low Hammer", type: ExType.DURATION, defaultDescription: "Overhead chop to neck, then low strike", durationSec: 45 },
  "kx-step-drag-claw-punch": { id: "kx-step-drag-claw-punch", name: "Step Drag/Claw/Low Punch", type: ExType.DURATION, defaultDescription: "Forward step drag with claw strike and low punch", durationSec: 45 },
  "kx-high-blocks": { id: "kx-high-blocks", name: "High Blocks", type: ExType.DURATION, defaultDescription: "Forearm blocks at 45-degree angle above head", durationSec: 30 },
  "kx-inward-blocks": { id: "kx-inward-blocks", name: "Inward Blocks", type: ExType.DURATION, defaultDescription: "Blocking motion sweeping across chest inward", durationSec: 30 },
  "kx-outward-blocks": { id: "kx-outward-blocks", name: "Outward Blocks", type: ExType.DURATION, defaultDescription: "Outward blocking motion away from chest", durationSec: 30 },
  "kx-downward-blocks": { id: "kx-downward-blocks", name: "Downward Blocks", type: ExType.DURATION, defaultDescription: "Blocking at waist level downward", durationSec: 30 },
  "kx-star-blocks": { id: "kx-star-blocks", name: "Star Blocks", type: ExType.DURATION, defaultDescription: "All four blocks in rapid succession", durationSec: 30 },
  "kx-high-block-low-punch": { id: "kx-high-block-low-punch", name: "High Block/Low Punch", type: ExType.DURATION, defaultDescription: "High block followed by cross punch", durationSec: 45 },
  "kx-knee-back-kick": { id: "kx-knee-back-kick", name: "Knee/Back Kick", type: ExType.DURATION, defaultDescription: "High knee followed by back kick", durationSec: 45 },
  "kx-knuckle-front-back-kick": { id: "kx-knuckle-front-back-kick", name: "Back Knuckle/Ball Kick/Back Kick", type: ExType.DURATION, defaultDescription: "Back fist, front kick, back kick combo", durationSec: 45 },
  "kx-hook-upper-side-kick": { id: "kx-hook-upper-side-kick", name: "Hook/Uppercut/Low Side Kick", type: ExType.DURATION, defaultDescription: "Punch combo finishing with low side kick", durationSec: 45 },
  "kx-elbow-series": { id: "kx-elbow-series", name: "Elbow Series", type: ExType.DURATION, defaultDescription: "Three elbows: straight up, side strike, back across", durationSec: 45 },
  "kx-vertical-punches": { id: "kx-vertical-punches", name: "Vertical Punches", type: ExType.DURATION, defaultDescription: "Vertical fist crosses with increasing speed", durationSec: 45 },

  // === YOGA X (Disc 4) — key poses ===
  "yx-runners-pose": { id: "yx-runners-pose", name: "Runner's Pose", type: ExType.DURATION, defaultDescription: "Low lunge, palms flat on floor, stretch hip flexors", durationSec: 100 },
  "yx-crescent-pose": { id: "yx-crescent-pose", name: "Crescent Pose", type: ExType.DURATION, defaultDescription: "From runner's pose, sweep arms overhead", durationSec: 90 },
  "yx-warrior-one": { id: "yx-warrior-one", name: "Warrior One", type: ExType.DURATION, defaultDescription: "Front knee bent 90 degrees, back leg straight, arms overhead", durationSec: 90 },
  "yx-warrior-two": { id: "yx-warrior-two", name: "Warrior Two", type: ExType.DURATION, defaultDescription: "Arms open wide, front knee bent, gaze over front hand", durationSec: 90 },
  "yx-reverse-warrior": { id: "yx-reverse-warrior", name: "Reverse Warrior", type: ExType.DURATION, defaultDescription: "Back hand slides down leg, front arm reaches overhead", durationSec: 90 },
  "yx-triangle": { id: "yx-triangle", name: "Triangle Pose", type: ExType.DURATION, defaultDescription: "Front leg straight, reach hand to shin/floor, other arm to sky", durationSec: 90 },
  "yx-twisting-triangle": { id: "yx-twisting-triangle", name: "Twisting Triangle", type: ExType.DURATION, defaultDescription: "Triangle variation with torso twist, opposite hand to floor", durationSec: 90 },
  "yx-chair-prayer-twist": { id: "yx-chair-prayer-twist", name: "Chair to Prayer Twist", type: ExType.DURATION, defaultDescription: "Sit into chair pose, then twist with hands in prayer", durationSec: 90 },
  "yx-right-angle-extended": { id: "yx-right-angle-extended", name: "Right-Angle Pose / Extended Side Angle", type: ExType.DURATION, defaultDescription: "Side angle stretch with arm extended, progress to bind", durationSec: 120 },
  "yx-prayer-twist-side-arm": { id: "yx-prayer-twist-side-arm", name: "Prayer Twist to Side Arm Balance", type: ExType.DURATION, defaultDescription: "Twist in low lunge transitioning to arm balance", durationSec: 60 },
  "yx-warrior-three-splits": { id: "yx-warrior-three-splits", name: "Warrior Three to Standing Splits", type: ExType.DURATION, defaultDescription: "Balance on one leg, body parallel; then fold to split", durationSec: 60 },
  "yx-half-moon-twist": { id: "yx-half-moon-twist", name: "Half Moon to Twisting Half Moon", type: ExType.DURATION, defaultDescription: "Balance on one leg with hand on floor, stack hips; then twist", durationSec: 90 },
  "yx-tree": { id: "yx-tree", name: "Tree Pose", type: ExType.DURATION, defaultDescription: "Stand on one leg, other foot on inner thigh, hands prayer/overhead", durationSec: 90 },
  "yx-royal-dancer": { id: "yx-royal-dancer", name: "Royal Dancer", type: ExType.DURATION, defaultDescription: "Stand on one leg, grab back foot, extend forward arm, arch back", durationSec: 90 },
  "yx-standing-leg-ext": { id: "yx-standing-leg-ext", name: "Standing Leg Extension", type: ExType.DURATION, defaultDescription: "Stand on one leg, extend other forward holding foot", durationSec: 60 },
  "yx-crane": { id: "yx-crane", name: "Crane", type: ExType.DURATION, defaultDescription: "Place knees on elbows, lean forward to balance on hands", durationSec: 60 },
  "yx-seated-spinal-stretch": { id: "yx-seated-spinal-stretch", name: "Seated Spinal Stretch", type: ExType.DURATION, defaultDescription: "Seated twist with one leg extended, other crossed over", durationSec: 60 },
  "yx-cat-stretch": { id: "yx-cat-stretch", name: "Cat Stretch", type: ExType.DURATION, defaultDescription: "Tabletop position, arch back up and down", durationSec: 50 },
  "yx-frog": { id: "yx-frog", name: "Frog", type: ExType.DURATION, defaultDescription: "Wide-knee squat/groin stretch on the floor", durationSec: 60 },
  "yx-bridge-wheel": { id: "yx-bridge-wheel", name: "Bridge or Wheel", type: ExType.DURATION, defaultDescription: "Lying on back, press hips up (bridge) or full backbend", durationSec: 60 },
  "yx-plough-shoulderstand": { id: "yx-plough-shoulderstand", name: "Plough to Shoulder Stand", type: ExType.DURATION, defaultDescription: "Legs over head, then up into shoulder stand with leg variations", durationSec: 110 },
  "yx-table": { id: "yx-table", name: "Table", type: ExType.DURATION, defaultDescription: "Reverse tabletop, hips pressed up, arms behind", durationSec: 60 },
  "yx-cobbler": { id: "yx-cobbler", name: "Cobbler Pose", type: ExType.DURATION, defaultDescription: "Seated, soles of feet together, knees open, fold forward", durationSec: 60 },
  "yx-one-leg-hamstring": { id: "yx-one-leg-hamstring", name: "One-Legged Hamstring Stretch", type: ExType.DURATION, defaultDescription: "Seated, one leg extended, fold forward", durationSec: 60 },
  "yx-two-leg-hamstring": { id: "yx-two-leg-hamstring", name: "Two-Legged Hamstring Stretch", type: ExType.DURATION, defaultDescription: "Seated, both legs extended, fold forward", durationSec: 60 },
  "yx-touch-the-sky": { id: "yx-touch-the-sky", name: "Touch the Sky", type: ExType.DURATION, defaultDescription: "Yoga belly: lying on back, crunch up reaching toward ceiling", durationSec: 45 },
  "yx-boat": { id: "yx-boat", name: "Boat Pose", type: ExType.DURATION, defaultDescription: "Seated V-shape, legs and torso lifted, arms extended", durationSec: 45 },
  "yx-half-boat": { id: "yx-half-boat", name: "Half Boat", type: ExType.DURATION, defaultDescription: "Lower version of boat, more ab engagement", durationSec: 45 },
  "yx-scissor": { id: "yx-scissor", name: "Scissor", type: ExType.DURATION, defaultDescription: "Lying on back, alternate raising legs in scissor motion", durationSec: 45 },
  "yx-torso-twist-hold": { id: "yx-torso-twist-hold", name: "Torso Twist Hold", type: ExType.DURATION, defaultDescription: "Seated twist with legs elevated", durationSec: 45 },
  "yx-deep-torso-twist": { id: "yx-deep-torso-twist", name: "Deep Torso Twist Hold", type: ExType.DURATION, defaultDescription: "Deeper version of torso twist", durationSec: 45 },

  // === X STRETCH (Disc 7) ===
  "xs-sun-salutations": { id: "xs-sun-salutations", name: "Sun Salutations", type: ExType.DURATION, defaultDescription: "Yoga warm-up flow: forward fold, plank, up dog, down dog", durationSec: 120 },
  "xs-neck-stretch": { id: "xs-neck-stretch", name: "Neck Stretch", type: ExType.DURATION, defaultDescription: "Gentle neck stretches, tilting ear to shoulder each side", durationSec: 60 },
  "xs-back-up-the-car": { id: "xs-back-up-the-car", name: "Back Up the Car", type: ExType.DURATION, defaultDescription: "Look over shoulder as if backing up; rotational neck/back stretch", durationSec: 60 },
  "xs-head-rolls": { id: "xs-head-rolls", name: "Head Rolls", type: ExType.DURATION, defaultDescription: "Slow circular head rolls to release neck tension", durationSec: 60 },
  "xs-expand-contract": { id: "xs-expand-contract", name: "Expand/Contract", type: ExType.DURATION, defaultDescription: "Open chest wide then round forward, stretching back and chest", durationSec: 60 },
  "xs-topas-shoulder": { id: "xs-topas-shoulder", name: "Topas Shoulder Stretch", type: ExType.DURATION, defaultDescription: "Deep shoulder stretch", durationSec: 60 },
  "xs-wrist-forearm-flex": { id: "xs-wrist-forearm-flex", name: "Wrist-Forearm Flex Stretch", type: ExType.DURATION, defaultDescription: "Extend arm, pull fingers back to stretch forearm", durationSec: 45 },
  "xs-dreya-forearm": { id: "xs-dreya-forearm", name: "Dreya Forearm Stretch", type: ExType.DURATION, defaultDescription: "Forearm/wrist stretch variation", durationSec: 45 },
  "xs-arm-circles": { id: "xs-arm-circles", name: "Arm Circles", type: ExType.DURATION, defaultDescription: "Forward and backward arm circles of increasing size", durationSec: 60 },
  "xs-shoulder-tricep-combo": { id: "xs-shoulder-tricep-combo", name: "Shoulder-Triceps Combo Stretch", type: ExType.DURATION, defaultDescription: "Cross-body shoulder stretch + overhead triceps stretch", durationSec: 60 },
  "xs-ballistic-upper": { id: "xs-ballistic-upper", name: "Ballistic Stretches (Upper)", type: ExType.DURATION, defaultDescription: "Dynamic bouncing stretches for upper body", durationSec: 60 },
  "xs-standing-side-stretch": { id: "xs-standing-side-stretch", name: "Standing Side Stretch", type: ExType.DURATION, defaultDescription: "Reach one arm overhead and lean to the side", durationSec: 60 },
  "xs-roller": { id: "xs-roller", name: "Roller", type: ExType.DURATION, defaultDescription: "Roll on the floor like a ball, massaging the spine", durationSec: 60 },
  "xs-plough": { id: "xs-plough", name: "Plough", type: ExType.DURATION, defaultDescription: "Lying on back, bring legs overhead until toes touch floor behind head", durationSec: 60 },
  "xs-seated-spinal-stretch": { id: "xs-seated-spinal-stretch", name: "Seated Spinal Stretch", type: ExType.DURATION, defaultDescription: "Seated twist with legs extended", durationSec: 60 },
  "xs-cat-stretch": { id: "xs-cat-stretch", name: "Cat Stretch", type: ExType.DURATION, defaultDescription: "Tabletop, alternate arching and rounding spine", durationSec: 60 },
  "xs-glute-stretch": { id: "xs-glute-stretch", name: "Glute Stretch", type: ExType.DURATION, defaultDescription: "Floor-based glute/piriformis stretch (figure-4 or pigeon)", durationSec: 60 },
  "xs-wide-feet-hamstring": { id: "xs-wide-feet-hamstring", name: "Wide-Feet Forward Hamstring Stretch", type: ExType.DURATION, defaultDescription: "Wide stance, fold forward", durationSec: 60 },
  "xs-side-twist": { id: "xs-side-twist", name: "Side Twist", type: ExType.DURATION, defaultDescription: "Rotational stretch from a wide stance", durationSec: 60 },
  "xs-camel": { id: "xs-camel", name: "Camel", type: ExType.DURATION, defaultDescription: "Kneeling backbend, reach hands back to heels", durationSec: 60 },
  "xs-back-hero": { id: "xs-back-hero", name: "Back Hero", type: ExType.DURATION, defaultDescription: "Kneeling, lean back toward the floor (reclined hero)", durationSec: 60 },
  "xs-kenpo-quad-stretch": { id: "xs-kenpo-quad-stretch", name: "Kenpo Quad Stretch", type: ExType.DURATION, defaultDescription: "Standing quad stretch, pull foot to glute", durationSec: 60 },
  "xs-bow": { id: "xs-bow", name: "Bow", type: ExType.DURATION, defaultDescription: "Lying face down, grab ankles, lift chest and legs", durationSec: 60 },
  "xs-low-squat": { id: "xs-low-squat", name: "Low Squat", type: ExType.DURATION, defaultDescription: "Deep squat hold, stretching hips and ankles", durationSec: 60 },
  "xs-frog": { id: "xs-frog", name: "Frog", type: ExType.DURATION, defaultDescription: "Wide knees, press hips toward ground; inner thigh stretch", durationSec: 90 },
  "xs-single-leg-hamstring": { id: "xs-single-leg-hamstring", name: "Seated Single-Leg Hamstring Stretch", type: ExType.DURATION, defaultDescription: "One leg extended, fold forward", durationSec: 60 },
  "xs-two-leg-hamstring": { id: "xs-two-leg-hamstring", name: "Seated Two-Leg Hamstring Stretch", type: ExType.DURATION, defaultDescription: "Both legs extended, fold forward", durationSec: 60 },
  "xs-ballistic-hamstring": { id: "xs-ballistic-hamstring", name: "Ballistic Hamstring Stretch", type: ExType.DURATION, defaultDescription: "Dynamic bouncing hamstring stretch", durationSec: 60 },
  "xs-split-leg-hamstring": { id: "xs-split-leg-hamstring", name: "Split-Leg Hamstring Stretch", type: ExType.DURATION, defaultDescription: "Wide split position, forward fold", durationSec: 60 },
  "xs-toe-flexor": { id: "xs-toe-flexor", name: "Toe Flexor", type: ExType.DURATION, defaultDescription: "Stretch tops of feet and toe flexors", durationSec: 45 },
  "xs-downdog-calf": { id: "xs-downdog-calf", name: "Downward Dog with Calf Stretch", type: ExType.DURATION, defaultDescription: "Downward dog, pedal heels to stretch calves", durationSec: 60 },
  "xs-updog-ankle": { id: "xs-updog-ankle", name: "Upward Dog with Ankle Stretch", type: ExType.DURATION, defaultDescription: "Upward dog, tops of feet flat, stretching ankles", durationSec: 60 },
  "xs-childs-pose-lr": { id: "xs-childs-pose-lr", name: "Child's Pose with Side Stretches", type: ExType.DURATION, defaultDescription: "Child's pose, walk hands to each side for lateral stretch", durationSec: 90 },

  // === CARDIO X (Disc 11) ===
  "cx-sun-salutations": { id: "cx-sun-salutations", name: "Sun Salutations", type: ExType.DURATION, defaultDescription: "Yoga flow: arms to sky, fold down, plank, up dog, down dog", durationSec: 170 },
  "cx-runners-pose": { id: "cx-runners-pose", name: "Runner's Pose", type: ExType.DURATION, defaultDescription: "From plank, swing leg forward into low lunge", durationSec: 75 },
  "cx-warrior-one": { id: "cx-warrior-one", name: "Warrior One", type: ExType.DURATION, defaultDescription: "From runner's pose, raise arms overhead", durationSec: 80 },
  "cx-warrior-two": { id: "cx-warrior-two", name: "Warrior Two", type: ExType.DURATION, defaultDescription: "Open arms to sides, front knee bent, gaze over hand", durationSec: 83 },
  "cx-reverse-warrior": { id: "cx-reverse-warrior", name: "Reverse Warrior", type: ExType.DURATION, defaultDescription: "Warrior One through Two into reverse warrior", durationSec: 110 },
  "cx-ball-kick": { id: "cx-ball-kick", name: "Ball Kick", type: ExType.DURATION, defaultDescription: "Simple forward kick, no higher than waist", durationSec: 70 },
  "cx-hook-upper-side-kick": { id: "cx-hook-upper-side-kick", name: "Hook/Uppercut/Side Kick", type: ExType.DURATION, defaultDescription: "Punch combo followed by controlled side kick", durationSec: 40 },
  "cx-knuckle-front-back-kick": { id: "cx-knuckle-front-back-kick", name: "Knuckles/Front Kick/Back Kick", type: ExType.DURATION, defaultDescription: "Strikes with directional kicks", durationSec: 55 },
  "cx-jab-cross-hook-upper": { id: "cx-jab-cross-hook-upper", name: "Jab/Cross/Hook/Uppercut", type: ExType.DURATION, defaultDescription: "Four-punch combo with hip rotation", durationSec: 65 },
  "cx-three-direction-kicks": { id: "cx-three-direction-kicks", name: "Three Direction Kicks", type: ExType.DURATION, defaultDescription: "Front, side, and back kicks maintaining balance", durationSec: 25 },
  "cx-airborne-heisman": { id: "cx-airborne-heisman", name: "Airborne Heisman", type: ExType.DURATION, defaultDescription: "Leap side-to-side into Heisman pose", durationSec: 30 },
  "cx-swing-kicks": { id: "cx-swing-kicks", name: "Swing Kicks", type: ExType.DURATION, defaultDescription: "Leg swings over imaginary obstacle", durationSec: 30 },
  "cx-jump-shots": { id: "cx-jump-shots", name: "Jump Shots", type: ExType.DURATION, defaultDescription: "Simulated basketball jump shots", durationSec: 30 },
  "cx-monster-truck-tires": { id: "cx-monster-truck-tires", name: "Monster Truck Tires", type: ExType.DURATION, defaultDescription: "High-knee hops between imaginary tires", durationSec: 30 },
  "cx-wacky-jacks": { id: "cx-wacky-jacks", name: "Wacky Jacks", type: ExType.DURATION, defaultDescription: "Lateral leg kicks with overhead arm waving", durationSec: 30 },
  "cx-squat-x-press": { id: "cx-squat-x-press", name: "Squat Cross X-Press", type: ExType.DURATION, defaultDescription: "Wide squat touching ground, then reach for sky in X", durationSec: 43 },
  "cx-steam-engine": { id: "cx-steam-engine", name: "Steam Engine", type: ExType.DURATION, defaultDescription: "Hands behind head, elbow to opposite knee", durationSec: 78 },
  "cx-dreya-roll": { id: "cx-dreya-roll", name: "Dreya Roll", type: ExType.DURATION, defaultDescription: "Roll backward, roll forward to standing", durationSec: 60 },
  "cx-squat-run": { id: "cx-squat-run", name: "Squat Run", type: ExType.DURATION, defaultDescription: "Staggered squat with running arm motion", durationSec: 60 },
  "cx-superman-banana": { id: "cx-superman-banana", name: "Superman/Banana", type: ExType.DURATION, defaultDescription: "Alternate prone superman and supine banana hold", durationSec: 60 },
};

/* ── Workout Definitions ── */
const WORKOUTS = [
  {
    id: "chest-and-back", name: "Chest & Back", category: "strength", icon: "\uD83D\uDCAA", disc: 1,
    exerciseIds: [
      "cb-standard-pushups","cb-wide-front-pullups","cb-military-pushups","cb-reverse-grip-chinups",
      "cb-wide-fly-pushups","cb-closed-grip-overhand-pullups","cb-decline-pushups","cb-heavy-pants",
      "cb-diamond-pushups","cb-lawnmowers","cb-dive-bomber-pushups","cb-back-flys",
      "cb-wide-front-pullups","cb-standard-pushups","cb-reverse-grip-chinups","cb-military-pushups",
      "cb-closed-grip-overhand-pullups","cb-wide-fly-pushups","cb-heavy-pants","cb-decline-pushups",
      "cb-lawnmowers","cb-diamond-pushups","cb-back-flys","cb-dive-bomber-pushups"
    ]
  },
  {
    id: "shoulders-and-arms", name: "Shoulders & Arms", category: "strength", icon: "\uD83D\uDCAA", disc: 3,
    exerciseIds: [
      "sa-alt-shoulder-press","sa-in-out-bicep-curls","sa-two-arm-tricep-kickback",
      "sa-alt-shoulder-press","sa-in-out-bicep-curls","sa-two-arm-tricep-kickback",
      "sa-deep-swimmers-press","sa-full-supination-curls","sa-chair-dips",
      "sa-deep-swimmers-press","sa-full-supination-curls","sa-chair-dips",
      "sa-upright-rows","sa-static-arm-curls","sa-flip-grip-kickbacks",
      "sa-upright-rows","sa-static-arm-curls","sa-flip-grip-kickbacks",
      "sa-two-angle-shoulder-flys","sa-crouching-cohen-curls","sa-lying-tricep-ext",
      "sa-two-angle-shoulder-flys","sa-crouching-cohen-curls","sa-lying-tricep-ext",
      "sa-in-out-shoulder-flys","sa-congdon-curls","sa-side-tri-rises",
      "sa-in-out-shoulder-flys","sa-congdon-curls","sa-side-tri-rises"
    ]
  },
  {
    id: "legs-and-back", name: "Legs & Back", category: "strength", icon: "\uD83E\uDDB5", disc: 5,
    exerciseIds: [
      "lb-balanced-lunges","lb-calf-raise-squats","lb-reverse-grip-chinups",
      "lb-super-skaters","lb-wall-squats","lb-wide-front-pullups",
      "lb-step-back-lunge","lb-alt-side-lunge","lb-closed-grip-pullups",
      "lb-single-leg-wall-squat","lb-deadlift-squats","lb-switch-grip-pullups",
      "lb-three-way-lunge","lb-sneaky-lunge","lb-reverse-grip-chinups",
      "lb-chair-salutations","lb-toe-roll-iso-lunge","lb-wide-front-pullups",
      "lb-groucho-walk","lb-calf-raises-toes-out","lb-calf-raises-parallel","lb-calf-raises-toes-in",
      "lb-closed-grip-pullups-2","lb-80-20-squats","lb-switch-grip-pullups-2"
    ]
  },
  {
    id: "core-synergistics", name: "Core Synergistics", category: "core", icon: "\uD83D\uDD25", disc: 8,
    exerciseIds: [
      "cs-stacked-staggered-pushups","cs-banana-rolls","cs-leaning-crescent-lunges","cs-squat-runs",
      "cs-sphinx-pushups","cs-bow-to-boat","cs-low-lateral-skaters","cs-lunge-reach",
      "cs-prison-cell-pushups","cs-side-hip-raise","cs-squat-xpress","cs-plank-chaturanga-run",
      "cs-walking-pushups","cs-superman-banana","cs-lunge-kickback-curl-press","cs-towel-hoppers",
      "cs-reach-high-under-pushups","cs-steam-engine","cs-dreya-rolls","cs-plank-chaturanga-iso",
      "cs-halfback","cs-table-dip-leg-raises"
    ]
  },
  {
    id: "chest-shoulders-triceps", name: "Chest, Shoulders & Triceps", category: "strength", icon: "\uD83D\uDCAA", disc: 9,
    exerciseIds: [
      "cst-slow-motion-3in1-pushups","cst-in-out-shoulder-flys","cst-chair-dips",
      "cst-plange-pushups","cst-pike-presses","cst-side-tri-rises",
      "cst-floor-flys","cst-scarecrows","cst-overhead-tricep-ext",
      "cst-two-twitch-pushups","cst-y-presses","cst-lying-tricep-ext",
      "cst-side-to-side-pushups","cst-pour-flys","cst-side-leaning-tricep-ext",
      "cst-one-arm-pushups","cst-weighted-circles","cst-throw-the-bomb",
      "cst-clap-plyo-pushups","cst-slo-mo-throws","cst-front-back-tricep-ext",
      "cst-one-arm-balance-pushups","cst-fly-row-presses","cst-dumbbell-cross-body-blows"
    ]
  },
  {
    id: "back-and-biceps", name: "Back & Biceps", category: "strength", icon: "\uD83D\uDCAA", disc: 10,
    exerciseIds: [
      "bb-wide-front-pullups","bb-lawnmowers","bb-twenty-ones","bb-one-arm-cross-body-curls",
      "bb-switch-grip-pullups","bb-elbows-out-lawnmowers","bb-standing-bicep-curls","bb-one-arm-concentration-curls",
      "bb-corn-cob-pullups","bb-reverse-grip-rows","bb-open-arm-curls","bb-static-arm-curls",
      "bb-towel-pullups","bb-congdon-locomotives","bb-crouching-cohen-curls","bb-one-arm-corkscrew-curls",
      "bb-chinups","bb-seated-bent-over-back-flys","bb-curl-up-hammer-downs","bb-hammer-curls",
      "bb-max-rep-pullups","bb-superman","bb-in-out-hammer-curls","bb-strip-set-curls"
    ]
  },
  {
    id: "ab-ripper-x", name: "Ab Ripper X", category: "core", icon: "\uD83D\uDD25", disc: 12,
    exerciseIds: [
      "ab-in-outs","ab-seated-bicycles","ab-reverse-bicycles","ab-crunchy-frog",
      "ab-crossed-wide-leg-situps","ab-fifer-scissors","ab-hip-rock-n-raise","ab-pulse-ups",
      "ab-roll-up-v-up","ab-oblique-v-ups","ab-leg-climbs","ab-mason-twist"
    ]
  },
  {
    id: "plyometrics", name: "Plyometrics", category: "cardio", icon: "\u26A1", disc: 2,
    exerciseIds: [
      "plyo-jump-squats","plyo-run-stance-squats","plyo-airborne-heisman","plyo-swing-kicks",
      "plyo-squat-reach-jumps","plyo-squat-switch-pickups","plyo-double-airborne-heisman","plyo-circle-run",
      "plyo-jump-knee-tucks","plyo-mary-katherine-lunges","plyo-leapfrog-squats","plyo-twist-combo",
      "plyo-rock-star-hops","plyo-gap-jumps","plyo-squat-jacks","plyo-military-march",
      "plyo-run-squat-180","plyo-lateral-leapfrog-squats","plyo-monster-truck-tires","plyo-hot-foot",
      "plyo-pitch-and-catch","plyo-jump-shots","plyo-football-hero"
    ]
  },
  {
    id: "yoga-x", name: "Yoga X", category: "flexibility", icon: "\uD83E\uDDD8", disc: 4,
    exerciseIds: [
      "yx-runners-pose","yx-crescent-pose","yx-warrior-one","yx-warrior-two",
      "yx-reverse-warrior","yx-triangle","yx-twisting-triangle","yx-chair-prayer-twist",
      "yx-right-angle-extended","yx-prayer-twist-side-arm","yx-warrior-three-splits","yx-half-moon-twist",
      "yx-tree","yx-royal-dancer","yx-standing-leg-ext",
      "yx-crane","yx-seated-spinal-stretch","yx-cat-stretch","yx-frog",
      "yx-bridge-wheel","yx-plough-shoulderstand","yx-table","yx-cobbler",
      "yx-one-leg-hamstring","yx-two-leg-hamstring",
      "yx-touch-the-sky","yx-boat","yx-half-boat","yx-scissor",
      "yx-torso-twist-hold","yx-deep-torso-twist","yx-touch-the-sky"
    ]
  },
  {
    id: "kenpo-x", name: "Kenpo X", category: "cardio", icon: "\uD83E\uDD4B", disc: 6,
    exerciseIds: [
      "kx-twist-pivot","kx-twist-pivot-hook-upper","kx-jabs","kx-jab-cross",
      "kx-jab-cross-hook","kx-jab-cross-hook-upper",
      "kx-step-drag-high-low","kx-jab-cross-switch","kx-hook-uppercut-switch",
      "kx-knee-kicks","kx-ball-kicks","kx-side-kicks",
      "kx-back-kicks","kx-three-direction-kicks","kx-high-sword-low-hammer","kx-step-drag-claw-punch",
      "kx-high-blocks","kx-inward-blocks","kx-outward-blocks","kx-downward-blocks","kx-star-blocks",
      "kx-high-block-low-punch","kx-knee-back-kick","kx-knuckle-front-back-kick",
      "kx-hook-upper-side-kick","kx-elbow-series","kx-vertical-punches"
    ]
  },
  {
    id: "x-stretch", name: "X Stretch", category: "flexibility", icon: "\uD83E\uDD38", disc: 7,
    exerciseIds: [
      "xs-sun-salutations","xs-neck-stretch","xs-back-up-the-car","xs-head-rolls",
      "xs-expand-contract","xs-topas-shoulder","xs-wrist-forearm-flex","xs-dreya-forearm",
      "xs-arm-circles","xs-shoulder-tricep-combo","xs-ballistic-upper","xs-standing-side-stretch",
      "xs-roller","xs-plough","xs-seated-spinal-stretch","xs-cat-stretch",
      "xs-glute-stretch","xs-wide-feet-hamstring","xs-side-twist","xs-camel",
      "xs-cat-stretch","xs-back-hero","xs-kenpo-quad-stretch","xs-bow",
      "xs-low-squat","xs-frog","xs-single-leg-hamstring","xs-two-leg-hamstring",
      "xs-ballistic-hamstring","xs-split-leg-hamstring","xs-toe-flexor",
      "xs-downdog-calf","xs-updog-ankle","xs-childs-pose-lr"
    ]
  },
  {
    id: "cardio-x", name: "Cardio X", category: "cardio", icon: "\u2764\uFE0F", disc: 11,
    exerciseIds: [
      "cx-sun-salutations","cx-runners-pose","cx-warrior-one","cx-warrior-two","cx-reverse-warrior",
      "cx-ball-kick","cx-hook-upper-side-kick","cx-knuckle-front-back-kick",
      "cx-jab-cross-hook-upper","cx-three-direction-kicks",
      "cx-airborne-heisman","cx-swing-kicks","cx-jump-shots","cx-monster-truck-tires","cx-wacky-jacks",
      "cx-squat-x-press","cx-steam-engine","cx-dreya-roll","cx-squat-run","cx-superman-banana"
    ]
  }
];
